name:                plutus-contract-nft
version:             0.1.0.0
license:             MIT
author:              "Daniel Firth"
maintainer:          "dan.firth@homotopic.tech"
copyright:           "Daniel Firth"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            NFT Contract For Plutus
category:            Plutus

description:         NFT Contract For Plutus

default-extensions:
- AllowAmbiguousTypes
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DoAndIfThenElse
- EmptyDataDecls
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- NoImplicitPrelude
- NumericUnderscores
- OverloadedStrings
- PatternGuards
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- TypeSynonymInstances
- ViewPatterns

dependencies:
- base >= 4.7 && < 5
- containers
- plutus-contract
- plutus-ledger
- plutus-ledger-api
- text
ghc-options:
- -Weverything
- -Werror
- -Wno-all-missed-specialisations
- -Wno-missing-import-lists
- -Wno-missing-local-signatures
- -Wno-missing-safe-haskell-mode
- -Wno-prepositive-qualified-module
- -Wno-safe
- -Wno-unsafe
- -Wno-unused-packages
- -fobject-code
- -fno-ignore-interface-pragmas
- -fno-omit-interface-pragmas
- -fno-specialise
- -fno-strictness

library:
  source-dirs: src

  dependencies:
  - plutus-ledger-constraints
  - plutus-minting-policy-nft
  - plutus-tx
  - yubihsm-ed-sign
