resolver: lts-18.28
packages:
- .

extra-deps:
- MissingH-1.5.0.0
- OddWord-1.0.2.0
- Unique-0.4.7.9
- async-timer-0.2.0.0
- beam-core-0.9.2.1
- beam-migrate-0.5.1.2
- beam-sqlite-0.5.1.2
- blaze-textual-0.2.2.1
- blockfrost-api-0.3.1.0
- blockfrost-client-core-0.2.0.0
- blockfrost-client-0.3.1.0
- canonical-json-0.6.0.0
- command-0.1.1
- composition-prelude-3.0.0.2
- cryptostore-0.2.1.0
- dependent-map-0.4.0.0
- dependent-sum-0.7.1.0
- dependent-sum-template-0.1.1.1
- docopt-0.7.0.7
- dom-lt-0.2.3
- ekg-0.4.0.15
- ekg-core-0.1.1.7
- ekg-json-0.1.0.6
- freer-simple-1.2.1.2
- generic-lens-2.2.1.0
- generic-lens-core-2.2.1.0
- gray-code-0.3.1
- hspec-2.9.4
- hspec-core-2.9.4
- io-streams-haproxy-1.0.1.0
- jwt-0.11.0
- lazy-search-0.1.2.1
- libsystemd-journal-1.4.5
- monoidal-containers-0.6.2.0
- moo-1.2
- network-3.1.2.7
- newtype-0.2.2.0
- nothunks-0.1.3
- partial-order-0.2.0.0
- pqueue-1.4.1.4
- protolude-0.3.0
- recursion-schemes-5.1.3
- row-types-1.0.1.2
- servant-multipart-client-0.12.1
- servant-options-0.1.0.0
- servant-subscriber-0.7.0.0
- servant-websockets-2.0.0
- size-based-0.1.2.0
- sqlite-simple-0.4.18.0
- snap-core-1.0.4.2
- snap-server-1.1.2.0
- statistics-linreg-0.3
- streaming-binary-0.3.0.1
- th-extras-0.0.0.6
- time-interval-0.1.1
- time-out-0.2
- transformers-except-0.1.2

 
- git: https://github.com/Quid2/flat.git
  commit: d32c2c0c0c3c38c41177684ade9febe92d279b06
- git: https://github.com/input-output-hk/purescript-bridge.git
  commit: 47a1f11825a0f9445e0f98792f79172efef66c00
- git: https://github.com/input-output-hk/servant-purescript.git
  commit: 44e7cacf109f84984cd99cd3faf185d161826963
- git: https://github.com/input-output-hk/cardano-crypto.git
  commit: f73079303f663e028288f9f4a9e08bcca39a923e
  # nix-sha256: sha256-2Fipex/WjIRMrvx6F3hjJoAeMtFd2wGnZECT0kuIB9k=
- git: https://github.com/input-output-hk/cardano-base
  commit: 41545ba3ac6b3095966316a99883d678b5ab8da8
  subdirs:
    - base-deriving-via
    - binary
    - binary/test
    - cardano-crypto-class
    - cardano-crypto-praos
    - cardano-crypto-tests
    - measures
    - orphans-deriving-via
    - slotting
    - strict-containers
- git: https://github.com/input-output-hk/cardano-prelude
  commit: bb4ed71ba8e587f672d06edf9d2e376f4b055555
  subdirs:
    - cardano-prelude
    - cardano-prelude-test
- git: https://github.com/input-output-hk/cardano-addresses
  commit: 71006f9eb956b0004022e80aadd4ad50d837b621
  subdirs:
    - command-line
    - core
- git: https://github.com/input-output-hk/cardano-wallet
  commit: f6d4db733c4e47ee11683c343b440552f59beff7
  subdirs:
    - lib/cli
    - lib/core
    - lib/core-integration
    - lib/dbvar
    - lib/launcher
    - lib/numeric
    - lib/shelley
    - lib/strict-non-empty-containers
    - lib/test-utils
    - lib/text-class
  # nix-sha256: sha256-3oeHsrAhDSSKBSzpGIAqmOcFmBdAJ5FR02UXPLb/Yz0=
- git: https://github.com/input-output-hk/ouroboros-network
  commit: 4fac197b6f0d2ff60dc3486c593b68dc00969fbf
  subdirs:
    - io-classes
    - io-sim
    - monoidal-synchronisation
    - network-mux
    - ntp-client
    - ouroboros-network
    - ouroboros-network-testing
    - ouroboros-network-framework
    - ouroboros-consensus
    - ouroboros-consensus-byron
    - ouroboros-consensus-cardano
    - ouroboros-consensus-protocol
    - ouroboros-consensus-shelley
    - strict-stm
    - typed-protocols
    - typed-protocols-cborg
    - typed-protocols-examples
- git: https://github.com/input-output-hk/iohk-monitoring-framework
  commit: 46f994e216a1f8b36fe4669b47b2a7011b0e153c
  subdirs:
    - iohk-monitoring
    - tracer-transformers
    - contra-tracer
    - plugins/backend-aggregation
    - plugins/backend-ekg
    - plugins/backend-monitoring
    - plugins/backend-trace-forwarder
    - plugins/scribe-systemd
  # nix-sha256: sha256-QE3QRpIHIABm+qCP/wP4epbUx0JmSJ9BMePqWEd3iMY=
- git: https://github.com/input-output-hk/cardano-ledger-specs
  commit: 1a9ec4ae9e0b09d54e49b2a40c4ead37edadcce5
  subdirs:
    - eras/alonzo/impl
    - eras/byron/chain/executable-spec
    - eras/byron/crypto
    - eras/byron/crypto/test
    - eras/byron/ledger/executable-spec
    - eras/byron/ledger/impl
    - eras/byron/ledger/impl/test
    - eras/shelley/impl
    - eras/shelley/test-suite
    - eras/shelley-ma/impl
    - libs/cardano-data
    - libs/cardano-ledger-core
    - libs/cardano-ledger-pretty
    - libs/cardano-protocol-tpraos
    - libs/compact-map
    - libs/non-integral
    - libs/set-algebra
    - libs/small-steps
    - libs/small-steps-test
  # nix-sha256: sha256-lRNfkGMHnpPO0T19FZY5BnuRkr0zTRZIkxZVgHH0fys=
- git: https://github.com/input-output-hk/cardano-node.git
  commit: 2b1d18c6c7b7142d9eebfec34da48840ed4409b6
  subdirs:
    - cardano-api
    - cardano-cli
    - cardano-git-rev
    - cardano-node
    - cardano-submit-api
    - cardano-testnet
    - trace-dispatcher
    - trace-forward
    - trace-resources
  # nix-sha256: sha256-V1Yx7/zjcx8qv9b5dje6vLJQe4sPLZvgEXJrX0SRV4A=
- git: https://github.com/input-output-hk/cardano-config
  commit: e9de7a2cf70796f6ff26eac9f9540184ded0e4e6
- git: https://github.com/input-output-hk/optparse-applicative
  commit: 7497a29cb998721a9068d5725d49461f2bba0e7a
  # nix-sha256: sha256-uQx+SEYsCH7JcG3xAT0eJck9yq3y0cvx49bvItLLer8=
- git: https://github.com/input-output-hk/Win32-network
  commit: 3825d3abf75f83f406c1f7161883c438dac7277d
- git: https://github.com/input-output-hk/goblins
  commit: cde90a2b27f79187ca8310b6549331e59595e7ba
- git: https://github.com/input-output-hk/plutus
  commit: 00a6eee2ed318fc2ba46c7672576e692196f2ada
  subdirs:
    - plutus-core
    - plutus-ledger-api
    - plutus-tx
    - plutus-tx-plugin
    - word-array
    - prettyprinter-configurable
    - stubs/plutus-ghc-stub
  # nix-sha256: sha256-d+4cuj8N6OkW2C6tN/oABfxVgd0q5vcvIoN9IhdS0/0=
- git: https://github.com/input-output-hk/plutus-apps
  commit: 310d848f7ea05884c75be55712ae97ce7579c3bb
  subdirs:
  - freer-extras
  - playground-common
  - plutus-chain-index
  - plutus-chain-index-core
  - plutus-contract
  - plutus-ledger
  - plutus-ledger-constraints
  - plutus-pab
  - plutus-pab-executables
  - plutus-playground-server
  - plutus-use-cases
  - quickcheck-dynamic
  - web-ghc
  # nix-sha256: sha256-9LEWRMoWdwTxm+OiAmXJVxVKf7dDAvgGJf9JrOR1P34=
- git: https://gitlab.homotopic.tech/plutus/minting-policies/osc
  commit: 0d2a00e358e33aabffb12c901a300ac0191dd200
  ref: v0.1.0.0
  # nix-sha256: sha256-mmDXPIY/juwavWIKW6XwYRVVT0JCUBLugzqu251OtG8=
- git: https://gitlab.homotopic.tech/plutus/minting-policies/nft
  commit: 3e3fe6494c78582047f0f0f70baa41fdb5161ae6
  ref: v0.1.0.0
  # nix-sha256: sha256-EBUv7GD1w1IiMeugHC7HfbTAzXoc3W2h/d+znhcl6pI=
